#!/usr/bin/env python3
"""Regenerate scripts/fact_views.sql from the streaming fact DDLs.

    python3 scripts/generate_fact_views.py

Each view dwh.v_<fact> = batch rows up to the last day the batch table has loaded
+ streaming rows after it. The column list is read from the CREATE TABLE in
spark_jobs/streaming/fact/<fact>.py (a copy of the batch job's DDL), so run this after
changing a fact's columns, then re-run the SQL file in ClickHouse.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FACTS = ["fact_trip", "fact_delivery_event", "fact_fuel_purchase", "fact_maintenance", "fact_safety_incident"]

HEADER = """-- Serving views: one per fact, combining the batch layer and the streaming (speed) layer.
-- GENERATED by scripts/generate_fact_views.py from spark_jobs/streaming/fact/*.py; don't edit by hand.
--
--   dwh.<fact>             batch table (daily DAG), loaded up to some day C
--   dwh.<fact>_streaming   streaming table, 72 h TTL
--   dwh.v_<fact>           batch rows with toDate(src_sys_create_date) <= C
--                          + streaming rows with toDate(src_sys_create_date) > C
--
-- C = the last day the batch table has loaded (max src_sys_create_date), not today() - 1,
-- so there's no gap between midnight and the moment the nightly batch run finishes.
-- Each row comes from exactly one side: the batch run for day D reads exactly the raw
-- partitions of D. `source` says which layer a row came from.
-- Needs both tables to exist. Re-run this file after changing either table's columns.
"""


def columns(ddl: str) -> list:
    """Column names of a CREATE TABLE, splitting only on top-level commas (types contain commas)."""
    body = ddl[ddl.index("(") + 1:ddl.rindex(") ENGINE") if ") ENGINE" in ddl else ddl.rindex(")")]
    names, depth, current = [], 0, ""
    for ch in body + ",":
        if ch == "," and depth == 0:
            token = current.strip()
            if token:
                names.append(token.split()[0])
            current = ""
            continue
        depth += ch == "("
        depth -= ch == ")"
        current += ch
    return names


def ddl_of(fact: str) -> str:
    src = (ROOT / "spark_jobs/streaming/fact" / f"{fact}.py").read_text()
    match = re.search(r'^DDL\s*=\s*"""(.*?)"""', src, re.S | re.M)
    ddl = match.group(1)
    return ddl[:ddl.index("ENGINE")].rstrip() + " ENGINE"   # the column block only


def view_sql(fact: str) -> str:
    cols = columns(ddl_of(fact))
    col_list = ",\n    ".join(cols)
    cutoff = f"(SELECT max(toDate(src_sys_create_date)) FROM dwh.{fact})"
    return f"""
        CREATE OR REPLACE VIEW dwh.v_{fact} AS
        SELECT
            {col_list},
            'batch' AS source
        FROM dwh.{fact} FINAL
        WHERE toDate(src_sys_create_date) <= {cutoff}
        UNION ALL
        SELECT
            {col_list},
            'streaming' AS source
        FROM dwh.{fact}_streaming FINAL
        WHERE toDate(src_sys_create_date) > {cutoff};
    """


def main():
    out = HEADER + "".join(view_sql(f) for f in FACTS)
    target = ROOT / "scripts/fact_views.sql"
    target.write_text(out)
    for f in FACTS:
        print(f"v_{f}: {len(columns(ddl_of(f)))} columns")
    print(f"wrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
